pipeline {
    agent any
    environment {
        AWS_REGION = "us-east-1"
        AWS_ACCOUNT_ID = "891249033661"
        ECR_REPO = "vprofileappimage"
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        ECR_URI = "${ECR_REGISTRY}/${ECR_REPO}"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    tools {
        maven 'maven-3.9.9'
        jdk 'JDK-17'
    }

    stages {
        stage('fetch code') {
            steps {
                git branch: 'main', url: 'https://github.com/KondepudiPriydarshan/AWS_Devops.git'
                echo 'Code fetched successfully.'
            }
        }
        
        stage('Build') {
            steps {
                dir('vprofile') {   
                sh 'mvn install'
                }
            }
        }
        
        stage('post-build') {
            steps {
                dir('vprofile') {   
                sh 'mkdir -p version'
                sh 'cp -r target/*.war version/'
                }
            }
        }
        
        stage('unit test') {
            steps {
                dir('vprofile') {   
                sh 'mvn test'
                }
            }
        }
        stage('checkstyle analysis') {  
            steps {
                dir('vprofile') {                   
                sh 'mvn checkstyle:checkstyle'
                 }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('vprofile') {
                script {
                    def scannerHome = tool 'sonar6.2'
                    withSonarQubeEnv('sonarserver') {
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=vprofile \
                        -Dsonar.projectName=vprofile \
                        -Dsonar.sources=src/main/java \
                        -Dsonar.tests=src/test/java \
                        -Dsonar.java.binaries=target/classes \
                        -Dsonar.junit.reportPaths=target/surefire-reports \
                        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
                        -Dsonar.checkstyle.reportPaths=target/checkstyle-result.xml
                        """
                    }
                }
                }
            }
        }
        
        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        
        stage('Upload Artifact to Nexus') {
            steps {
                dir('vprofile') {
                    script {
                        def warFile = sh(
                            script: "ls target/*.war | head -n 1",
                            returnStdout: true
                        ).trim()
                        
                        echo "Uploading artifact: ${warFile}"
                        
                        nexusArtifactUploader(
                            nexusVersion: 'nexus3',
                            protocol: 'http',
                            nexusUrl: '172.31.43.158:8081',
                            groupId: 'com.visualpathit',
                            version: "1.0.${BUILD_NUMBER}, ${BUILD_TIMESTAMP}",
                            repository: 'artifact-repository',
                            credentialsId: 'nexus-admin-login',
                            artifacts: [
                                [
                                    artifactId: 'vprofile',
                                    classifier: '',
                                    file: warFile,
                                    type: 'war'
                                ]
                            ]
                        )
                    }
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('vprofile/Docker-files/app/multistage') {
                sh '''
                docker build -t $ECR_REPO:$IMAGE_TAG .
                '''
                }
            }
        }
        stage('Login to ECR') {
                steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                        sh '''
                        aws ecr get-login-password --region $AWS_REGION \
                        | docker login --username AWS --password-stdin $ECR_URI
                        '''
                    }
                }
        }
        stage('Tag & Push Image') {
                steps {
                    sh '''
                    docker tag ${ECR_REPO}:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}
                docker tag ${ECR_REPO}:${IMAGE_TAG} ${ECR_URI}:latest

                docker push ${ECR_URI}:${IMAGE_TAG}
                docker push ${ECR_URI}:latest
                    '''
                }
        }
        stage('Deploy to ECS') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh '''
                    aws ecs update-service \
                    --cluster Vprof-cluster \
                    --service vprof-service  \
                    --force-new-deployment \
                    --region us-east-1
                    '''
                    }
            }
        }
    }
    post {  
        success {
            slackSend(
                channel: '#all-aws',
                color: 'good',
                botUser: true,
                message: """
                ✅ *BUILD SUCCESS*
                Job: ${env.JOB_NAME}
                Build: #${env.BUILD_NUMBER}
                Version: ${env.ARTIFACT_VERSION}
                """
            )
        }

        failure {
            slackSend(
                channel: '#all-aws',
                color: 'danger',
                botUser: true,
                message: """
                ❌ *BUILD FAILED*
                Job: ${env.JOB_NAME}
                Build: #${env.BUILD_NUMBER}
                Check Jenkins logs.
                """
            )
        }
        
    }

}

